version: '3.5'
services:
  ges_db:
    image: mysql:5.7
    ports:
     - "33306:3306"
    environment:
      MYSQL_DATABASE: dba_ges
      MYSQL_USER: user_ges
      MYSQL_PASSWORD: 97Emc@l1
      MYSQL_ROOT_PASSWORD: 97Emc@l1
    volumes:
      - ./data_mysql:/var/lib/mysql
  ges_django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_django_dir
    ports:
      - "8001:8000"
    depends_on:
      - ges_db
