# Generated by Django 3.2.5 on 2022-02-07 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='', regex='^[a-zA-Z0-9\\s,\\\\\\/-]*$')], verbose_name='Modelo del dispositivo')),
                ('serial', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='', regex='^[A-Za-z0-9\\s]+[A-Za-z0-9\\s]+$(\\.0-9+)?')], verbose_name='Serial del dispositivo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BsDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('Router', 'Router'), ('Switch', 'Switch'), ('Accespoint', 'Accespoint')], max_length=200, validators=[django.core.validators.RegexValidator(message='Los caracteres ingresados son invalidos.', regex='/^(?!.* $)[aA-zZ][aA-zZ ]+$/gm')], verbose_name='Dispositivo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen del dispositivo')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('description', models.TextField(validators=[django.core.validators.RegexValidator(regex='')], verbose_name='Descripcion del dispositivo')),
            ],
        ),
    ]
