# Generated by Django 3.2.5 on 2022-03-08 22:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=0, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='El componente digitado es incorrecto.', regex='^[a-zA-Z]+(\\s*[a-zA-Z]*[-.]?)*[a-zA-Z]+$')], verbose_name='Componente')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('E', 'ENTREGADO'), ('R', 'POR RECOGER'), ('D', 'DISPOSIBLE'), ('B', 'DADO DE BAJA')], max_length=15, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('name', models.CharField(choices=[('ROUTER', 'ROUTER'), ('SWITCH', 'SWITCH'), ('ACCESPOINT', 'ACCESPOINT'), ('MODEM', 'MODEM'), ('ONT', 'ONT')], max_length=12, verbose_name='Dispositivo')),
                ('brand', models.CharField(choices=[('HUAWEI', 'HUAWEI'), ('ZTE', 'ZTE'), ('JUNIPER', 'JUNIPER'), ('FIBERHOME', 'FIBERHOME'), ('CISCO', 'CISCO')], max_length=12, verbose_name='Marca')),
                ('mac', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='La mac digitada es incorrecta', regex='^[0-9A-F]+$')], verbose_name='Mac')),
                ('model', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='El modelo digitado es incorrecto', regex='^[A-Z0-9\\s,\\\\/-]*$')], verbose_name='Modelo')),
                ('serial', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El serial digitado es incorrecto', regex='^[A-Za-z0-9\\s]+[A-Za-z0-9\\s]+$(\\.0-9+)?')], verbose_name='Serial')),
                ('value', models.DecimalField(decimal_places=3, max_digits=9, validators=[django.core.validators.RegexValidator(message='El valor ingresado es incorrecto', regex='[+-]?([0-9]*[.])?[0-9]+')], verbose_name='Valor')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='device/%Y/%m/%d', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('name', models.CharField(choices=[('VOZ', 'VOZ'), ('DATOS', 'DATOS'), ('VIDEO', 'VIDEO')], max_length=30, verbose_name='Producto')),
                ('cod_open', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El codigo ingresado es incorrecto', regex='^[0-9]*$')], verbose_name='Codigo Open')),
                ('device', multiselectfield.db.fields.MultiSelectField(choices=[('ROUTER', 'ROUTER'), ('SWITCH', 'SWITCH'), ('ACCESPOINT', 'ACCESPOINT'), ('MODEM', 'MODEM'), ('ONT', 'ONT')], max_length=34, verbose_name='Dispositivo')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.component', verbose_name='Componente')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El servicio digitado es incorrecto.', regex='^[a-zA-Z]+(\\s*[a-zA-Z]*[-.]?)*[a-zA-Z]+$')], verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='subService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El subservicio digitado es incorrecto.', regex='^[A-zA-Z0-9\\s]*$')], verbose_name='Subservicio')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Subservicio',
                'verbose_name_plural': 'Subservicios',
            },
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
        migrations.DeleteModel(
            name='BsDevices',
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.service', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.subservice', verbose_name='Subservicio'),
        ),
        migrations.AddField(
            model_name='component',
            name='sub_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.subservice', verbose_name='Subservicio'),
        ),
    ]
