# Generated by Django 3.2.5 on 2022-02-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_client_is_actived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_actived',
        ),
    ]
