# Generated by Django 3.2.5 on 2022-02-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_client_is_actived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='legal_representative',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='legal_representive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprise',
            name='niche',
            field=models.CharField(default=1, max_length=50, verbose_name='Nicho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprise',
            name='segment',
            field=models.CharField(default=1, max_length=50, verbose_name='Segmento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='state',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado'),
        ),
    ]
