# Generated by Django 3.2.5 on 2022-02-10 16:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_auto_20220209_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Segmento')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
            },
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='niche',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default=1, max_length=150, verbose_name='Direccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.RegexValidator(message='Numero digitado incorrectamente', regex='^([\\d]{5,5})\\s?([\\d]){5,5}$')], verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='legal_representive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Representante legal'),
        ),
        migrations.CreateModel(
            name='Niche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nicho')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.segment')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
            },
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.segment'),
        ),
    ]
