# Generated by Django 3.2.5 on 2022-02-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_auto_20220210_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='niche',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.niche', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.segment', verbose_name='Empresa'),
        ),
    ]
