# Generated by Django 3.2.5 on 2022-02-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_auto_20220210_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='niche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.niche', verbose_name='Nicho'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.segment', verbose_name='Segmento'),
        ),
    ]
