# Generated by Django 3.2.5 on 2022-02-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_auto_20220210_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niche',
            options={'verbose_name': 'Nicho', 'verbose_name_plural': 'Nichos'},
        ),
    ]
