# Generated by Django 3.2.5 on 2022-03-08 21:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_niche_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('Cali', 'Cali'), ('Palmira', 'Palmira'), ('Yumbo', 'Yumbo'), ('Candelaria', 'Candelaria'), ('Puerto tejada', 'Puerto tejada'), ('Jamundi', 'Jamundi')], max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nombre digitado incorrectamente', regex='^[A-Za-z ]{3,50}$')], verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='niche',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nicho digitado incorrectamente', regex='^[A-Za-z ]{3,500}$')], verbose_name='Nicho'),
        ),
        migrations.AlterField(
            model_name='niche',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.segment', verbose_name='Segmento'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Segmento digitado incorrectamente', regex='^[A-Za-z ]{3,500}$')], verbose_name='Segmento'),
        ),
    ]
