# Generated by Django 3.2.5 on 2022-03-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_auto_20220308_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='generating_via',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='group_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='group_type',
            field=models.CharField(blank=True, choices=[('Bloque', 'Bloque'), ('Bodega', 'Bodega'), ('Etapa', 'Etapa'), ('Localidad', 'Localidad'), ('Lote', 'Lote'), ('Parcelacion', 'Parcelacion'), ('Pasaje', 'Pasaje'), ('Sector', 'Sector'), ('Torre', 'Torre'), ('Unidad', 'Unidad')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='grouped',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='no_via',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='number_terminal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='prefix',
            field=models.CharField(choices=[(' ', 'NA'), ('Bis', 'Bis'), ('Norte', 'Norte'), ('Oeste', 'Oeste')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='suffix',
            field=models.CharField(choices=[(' ', 'NA'), ('Bis', 'Bis'), ('Norte', 'Norte'), ('Oeste', 'Oeste')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='type_terminal',
            field=models.CharField(blank=True, choices=[('Administracion', 'Administracion'), ('Almacen', 'Almacen'), ('Apartamento', 'Apartamento'), ('Cabaña', 'Cabaña'), ('Casa', 'Casa'), ('Local', 'Local'), ('Pasaje', 'Pasaje'), ('Oficina', 'Oficina'), ('Porteria', 'Porteria'), ('Salon', 'Salon')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='via',
            field=models.CharField(choices=[('Calle', 'Calle'), ('Carrera', 'Carrera'), ('Avenida', 'Avenida'), ('Diagonal', 'Transversal'), ('Diagonal', 'Diagonal')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='generating_via',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='group_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='group_type',
            field=models.CharField(blank=True, choices=[('Bloque', 'Bloque'), ('Bodega', 'Bodega'), ('Etapa', 'Etapa'), ('Localidad', 'Localidad'), ('Lote', 'Lote'), ('Parcelacion', 'Parcelacion'), ('Pasaje', 'Pasaje'), ('Sector', 'Sector'), ('Torre', 'Torre'), ('Unidad', 'Unidad')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='grouped',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='no_via',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='number_terminal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='prefix',
            field=models.CharField(choices=[(' ', 'NA'), ('Bis', 'Bis'), ('Norte', 'Norte'), ('Oeste', 'Oeste')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='suffix',
            field=models.CharField(choices=[(' ', 'NA'), ('Bis', 'Bis'), ('Norte', 'Norte'), ('Oeste', 'Oeste')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='type_terminal',
            field=models.CharField(blank=True, choices=[('Administracion', 'Administracion'), ('Almacen', 'Almacen'), ('Apartamento', 'Apartamento'), ('Cabaña', 'Cabaña'), ('Casa', 'Casa'), ('Local', 'Local'), ('Pasaje', 'Pasaje'), ('Oficina', 'Oficina'), ('Porteria', 'Porteria'), ('Salon', 'Salon')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='via',
            field=models.CharField(choices=[('Calle', 'Calle'), ('Carrera', 'Carrera'), ('Avenida', 'Avenida'), ('Diagonal', 'Transversal'), ('Diagonal', 'Diagonal')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Headquarters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('h_name', models.CharField(max_length=50, verbose_name='Nombre de la sede')),
                ('via', models.CharField(choices=[('Calle', 'Calle'), ('Carrera', 'Carrera'), ('Avenida', 'Avenida'), ('Diagonal', 'Transversal'), ('Diagonal', 'Diagonal')], max_length=50)),
                ('no_via', models.CharField(max_length=50)),
                ('prefix', models.CharField(choices=[(' ', 'NA'), ('Bis', 'Bis'), ('Norte', 'Norte'), ('Oeste', 'Oeste')], max_length=50)),
                ('suffix', models.CharField(choices=[(' ', 'NA'), ('Bis', 'Bis'), ('Norte', 'Norte'), ('Oeste', 'Oeste')], max_length=50)),
                ('generating_via', models.CharField(max_length=50)),
                ('city', models.CharField(choices=[('Cali', 'Cali'), ('Palmira', 'Palmira'), ('Yumbo', 'Yumbo'), ('Candelaria', 'Candelaria'), ('Puerto tejada', 'Puerto tejada'), ('Jamundi', 'Jamundi')], max_length=50, verbose_name='Ciudad')),
                ('grouped', models.CharField(blank=True, max_length=50, null=True)),
                ('group_type', models.CharField(blank=True, choices=[('Bloque', 'Bloque'), ('Bodega', 'Bodega'), ('Etapa', 'Etapa'), ('Localidad', 'Localidad'), ('Lote', 'Lote'), ('Parcelacion', 'Parcelacion'), ('Pasaje', 'Pasaje'), ('Sector', 'Sector'), ('Torre', 'Torre'), ('Unidad', 'Unidad')], max_length=50, null=True)),
                ('group_number', models.CharField(blank=True, max_length=50, null=True)),
                ('type_terminal', models.CharField(blank=True, choices=[('Administracion', 'Administracion'), ('Almacen', 'Almacen'), ('Apartamento', 'Apartamento'), ('Cabaña', 'Cabaña'), ('Casa', 'Casa'), ('Local', 'Local'), ('Pasaje', 'Pasaje'), ('Oficina', 'Oficina'), ('Porteria', 'Porteria'), ('Salon', 'Salon')], max_length=50, null=True)),
                ('number_terminal', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(max_length=50, verbose_name='Nombre de contacto')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='Telefono de contacto')),
                ('contact_email', models.CharField(max_length=50, verbose_name='Email de contacto')),
                ('observations', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['id'],
            },
        ),
    ]
