# Generated by Django 3.2.5 on 2022-03-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_auto_20220311_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='headquarters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp.headquarters', verbose_name='Sedes'),
            preserve_default=False,
        ),
    ]
