# Generated by Django 3.2.5 on 2022-03-17 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_auto_20220317_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='dir_server',
            field=models.CharField(default=1, max_length=40, validators=[django.core.validators.RegexValidator(message='Por favor,ingrese una direccion valida', regex='^[aA-zZ0-9\\s,\\\\/.-:]*$')], verbose_name='Dir Server'),
            preserve_default=False,
        ),
    ]
